### ISSUE TITLE
and replace with these

### ISSUE THREAD

**Issue by Hr46ph** [iwDevOps/RockyLinux8-Kickstart-iso#1]
Hello :).

I am following your steps because I need to automate some deployments with kickstarts. This is one of the options I am exploring.

In your guide you mention the following:
```Add these three files to the corresponding directories. Except for the ks.cfg, the other files are present, so delete them and add these.```

But where are "these"? The repo is empty besides the readme. I have a kickstart (I generate them with ansible and jinja template) but the other 2 are essential to properly boot with the kickstart file.

Are you able to share those as well?

Thanks for your time!

**Comment by mechanicus01** [comment]
Hello, yes sorry, I did not upload them, but the three files I was referring to are: kickstart ks,cfg, grub.cfg, and isolinux.cfg files. 

If you have your own kickstart file use that instead. My ks.cfg file is customized for my environment so it would not help you much. Search Google for "Red Hat kickstart file" for more info.  The other two  files- isolinux.cfg and grub.cfg - you can use the default ones. I customized all three files, which is why I said replace them.

**Comment by Hr46ph** [comment]
Thanks, appreciate the reply even though its somewhat delayed :)

Apologies if I didn't wait for an answer ;) but I have since moved on to another method as building iso's seemed unreliable and is too slow, its also maintenance heavy. I am now using Packer which only requires a kickstart (or preseed or whatever distro uses for unattended). I am currenty building 10 hosts in parallel and it finishes within 10 minutes. Building a single iso took longer than that.

Cheers! 😄
